/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Guthenberg;

import static Guthenberg.Form.Login_uyarı;
import static Guthenberg.Guthenberg.AramaSonuçları;
import static Guthenberg.Guthenberg.AramaSonuçları_numbers;
import static Guthenberg.Guthenberg.bks;
import static Guthenberg.Guthenberg.book1_;
import static Guthenberg.Guthenberg.book2_;
import static Guthenberg.Guthenberg.book3_;
import static Guthenberg.Guthenberg.book4_;
import static Guthenberg.Guthenberg.book5_;
import static Guthenberg.Guthenberg.book6_;
import static Guthenberg.Guthenberg.book7_;
import static Guthenberg.Guthenberg.book8_;
import static Guthenberg.Guthenberg.book9_;
import static Guthenberg.Guthenberg.book10_;
import static Guthenberg.Guthenberg.bookwindow;
import static Guthenberg.Guthenberg.i;
import static Guthenberg.Guthenberg.lines;
import static Guthenberg.Guthenberg.pages;
import static Guthenberg.Guthenberg.read_book_area;
import static Guthenberg.Guthenberg.search_area;
import static Guthenberg.Guthenberg.search_button;
import static Guthenberg.Guthenberg.select_field;
import static Guthenberg.Guthenberg.shelf;
import static Guthenberg.Guthenberg.users;
import static Guthenberg.User.AddBook;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.net.URLConnection;
import java.util.logging.Level;
import java.util.logging.Logger;
import static Guthenberg.User.searchBook;
import static Guthenberg.windowread.read_form;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.InputStreamReader;

/**
 *
 * @author Mert
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        book812312312 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        book1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        book2 = new javax.swing.JTextField();
        book3 = new javax.swing.JTextField();
        book4 = new javax.swing.JTextField();
        book5 = new javax.swing.JTextField();
        book6 = new javax.swing.JTextField();
        book7 = new javax.swing.JTextField();
        book8 = new javax.swing.JTextField();
        book9 = new javax.swing.JTextField();
        book10 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        read1 = new javax.swing.JButton();
        read2 = new javax.swing.JButton();
        read3 = new javax.swing.JButton();
        read4 = new javax.swing.JButton();
        read5 = new javax.swing.JButton();
        read6 = new javax.swing.JButton();
        read7 = new javax.swing.JButton();
        read8 = new javax.swing.JButton();
        read9 = new javax.swing.JButton();
        read10 = new javax.swing.JButton();
        Remove4 = new javax.swing.JButton();
        Remove5 = new javax.swing.JButton();
        Remove1 = new javax.swing.JButton();
        Remove2 = new javax.swing.JButton();
        Remove3 = new javax.swing.JButton();
        Remove6 = new javax.swing.JButton();
        Remove7 = new javax.swing.JButton();
        Remove8 = new javax.swing.JButton();
        Remove9 = new javax.swing.JButton();
        Remove10 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        search_field = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        select_box = new javax.swing.JTextField();
        read = new javax.swing.JButton();
        add = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 255, 153));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("SIGN OUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ChangePassword");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        book1.setFont(new java.awt.Font("Berlin Sans FB", 2, 14)); // NOI18N
        book1.setForeground(new java.awt.Color(0, 0, 255));
        book1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        book1.setName(""); // NOI18N
        book1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(51, 51, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gutenberg Library");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        book2.setFont(new java.awt.Font("Berlin Sans FB", 2, 14)); // NOI18N
        book2.setForeground(new java.awt.Color(0, 0, 255));
        book2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        book3.setFont(new java.awt.Font("Berlin Sans FB", 2, 14)); // NOI18N
        book3.setForeground(new java.awt.Color(0, 0, 255));
        book3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        book4.setFont(new java.awt.Font("Berlin Sans FB", 2, 14)); // NOI18N
        book4.setForeground(new java.awt.Color(0, 0, 255));
        book4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        book5.setFont(new java.awt.Font("Berlin Sans FB", 2, 14)); // NOI18N
        book5.setForeground(new java.awt.Color(0, 0, 255));
        book5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        book5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book5ActionPerformed(evt);
            }
        });

        book6.setFont(new java.awt.Font("Berlin Sans FB", 2, 14)); // NOI18N
        book6.setForeground(new java.awt.Color(0, 0, 255));
        book6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        book7.setFont(new java.awt.Font("Berlin Sans FB", 2, 14)); // NOI18N
        book7.setForeground(new java.awt.Color(0, 0, 255));
        book7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        book7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book7ActionPerformed(evt);
            }
        });

        book8.setFont(new java.awt.Font("Berlin Sans FB", 2, 14)); // NOI18N
        book8.setForeground(new java.awt.Color(0, 0, 255));
        book8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        book9.setFont(new java.awt.Font("Berlin Sans FB", 2, 14)); // NOI18N
        book9.setForeground(new java.awt.Color(0, 0, 255));
        book9.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        book10.setFont(new java.awt.Font("Berlin Sans FB", 2, 14)); // NOI18N
        book10.setForeground(new java.awt.Color(0, 0, 255));
        book10.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );

        read1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        read1.setForeground(new java.awt.Color(0, 0, 102));
        read1.setText("Read");
        read1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read1ActionPerformed(evt);
            }
        });

        read2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        read2.setForeground(new java.awt.Color(0, 0, 102));
        read2.setText("Read");
        read2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read2ActionPerformed(evt);
            }
        });

        read3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        read3.setForeground(new java.awt.Color(0, 0, 102));
        read3.setText("Read");
        read3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read3ActionPerformed(evt);
            }
        });

        read4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        read4.setForeground(new java.awt.Color(0, 0, 102));
        read4.setText("Read");
        read4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read4ActionPerformed(evt);
            }
        });

        read5.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        read5.setForeground(new java.awt.Color(0, 0, 102));
        read5.setText("Read");
        read5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read5ActionPerformed(evt);
            }
        });

        read6.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        read6.setForeground(new java.awt.Color(0, 0, 102));
        read6.setText("Read");
        read6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read6ActionPerformed(evt);
            }
        });

        read7.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        read7.setForeground(new java.awt.Color(0, 0, 102));
        read7.setText("Read");
        read7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read7ActionPerformed(evt);
            }
        });

        read8.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        read8.setForeground(new java.awt.Color(0, 0, 102));
        read8.setText("Read");
        read8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read8ActionPerformed(evt);
            }
        });

        read9.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        read9.setForeground(new java.awt.Color(0, 0, 102));
        read9.setText("Read");
        read9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read9ActionPerformed(evt);
            }
        });

        read10.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        read10.setForeground(new java.awt.Color(0, 0, 102));
        read10.setText("Read");
        read10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read10ActionPerformed(evt);
            }
        });

        Remove4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        Remove4.setForeground(new java.awt.Color(51, 0, 0));
        Remove4.setText("Remove");
        Remove4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remove4ActionPerformed(evt);
            }
        });

        Remove5.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        Remove5.setForeground(new java.awt.Color(51, 0, 0));
        Remove5.setText("Remove");
        Remove5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remove5ActionPerformed(evt);
            }
        });

        Remove1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        Remove1.setForeground(new java.awt.Color(51, 0, 0));
        Remove1.setText("Remove");
        Remove1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remove1ActionPerformed(evt);
            }
        });

        Remove2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        Remove2.setForeground(new java.awt.Color(51, 0, 0));
        Remove2.setText("Remove");
        Remove2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remove2ActionPerformed(evt);
            }
        });

        Remove3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        Remove3.setForeground(new java.awt.Color(51, 0, 0));
        Remove3.setText("Remove");
        Remove3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remove3ActionPerformed(evt);
            }
        });

        Remove6.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        Remove6.setForeground(new java.awt.Color(51, 0, 0));
        Remove6.setText("Remove");
        Remove6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remove6ActionPerformed(evt);
            }
        });

        Remove7.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        Remove7.setForeground(new java.awt.Color(51, 0, 0));
        Remove7.setText("Remove");
        Remove7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remove7ActionPerformed(evt);
            }
        });

        Remove8.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        Remove8.setForeground(new java.awt.Color(51, 0, 0));
        Remove8.setText("Remove");
        Remove8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remove8ActionPerformed(evt);
            }
        });

        Remove9.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        Remove9.setForeground(new java.awt.Color(51, 0, 0));
        Remove9.setText("Remove");
        Remove9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remove9ActionPerformed(evt);
            }
        });

        Remove10.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        Remove10.setForeground(new java.awt.Color(51, 0, 0));
        Remove10.setText("Remove");
        Remove10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remove10ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SearchBook");

        search_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_fieldActionPerformed(evt);
            }
        });
        search_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                search_fieldKeyPressed(evt);
            }
        });

        search.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        select_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_boxActionPerformed(evt);
            }
        });
        select_box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                select_boxKeyPressed(evt);
            }
        });

        read.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        read.setText("Read");
        read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readActionPerformed(evt);
            }
        });

        add.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(book4)
                    .addComponent(book3)
                    .addComponent(book2)
                    .addComponent(book1)
                    .addComponent(book5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(read5)
                    .addComponent(read3)
                    .addComponent(read4)
                    .addComponent(read1)
                    .addComponent(read2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Remove5)
                    .addComponent(Remove3)
                    .addComponent(Remove4)
                    .addComponent(Remove1)
                    .addComponent(Remove2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Remove10)
                    .addComponent(Remove8)
                    .addComponent(Remove9)
                    .addComponent(Remove6)
                    .addComponent(Remove7))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(read10)
                    .addComponent(read8)
                    .addComponent(read9)
                    .addComponent(read6)
                    .addComponent(read7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(book10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(book8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(book9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(book6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(book7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(search_field, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(select_box, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(read, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(book1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(book6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(book2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(book7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(book3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(book8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(book4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(book9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(book5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(book10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(read6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(read7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(read8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(read9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(read10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(read1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(read2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(read3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(read4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(read5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Remove1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Remove2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Remove3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Remove4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Remove5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Remove6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Remove7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Remove8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Remove9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Remove10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(search_field)
                    .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(select_box, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(read, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void book7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book7ActionPerformed

    private void read6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read6ActionPerformed
        int b;
        for (b = 0; b < pages.size(); b++) {
            if (getName().equals(pages.get(b).getName())) {
                break;
            }
        }
        users.get(b).ReadBook(6);        // TODO add your handling code here:
    }//GEN-LAST:event_read6ActionPerformed

    private void search_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_fieldActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int s;
        for (s = 0; s < pages.size(); s++) {
            if (pages.get(s).getName().equals(getName())) {
                break;
            }
        }
        pages.remove(s);
        users.remove(s);
        book1_.remove(s);
        book2_.remove(s);
        book3_.remove(s);
        book4_.remove(s);
        book5_.remove(s);
        book6_.remove(s);
        book7_.remove(s);
        book8_.remove(s);
        book9_.remove(s);
        book10_.remove(s);
        select_field.remove(s);
        search_area.remove(s);
        search_button.remove(s);
        read_book_area.remove(s);
        i = i - 1;
        Login_uyarı.setText("Session closed." + "-->" + getName());
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Form3().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        do {
            int l;
            for (l = 0; l < search_button.size(); l++) {
                if (getName().equals(search_button.get(l).getName())) {
                    break;
                }
            }

            try {
                Double.parseDouble(search_button.get(l).getText());
                search_button.get(l).setText("must be include character");
                break;
            } catch (NumberFormatException e) {

            }

            try {
                searchBook(getName(), search_button.get(l).getText());
            } catch (IOException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            }
        } while (false);

    }//GEN-LAST:event_searchActionPerformed

    private void search_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_fieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_fieldKeyPressed

    private void select_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_select_boxActionPerformed

    private void select_boxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_select_boxKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_select_boxKeyPressed

    private void readActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readActionPerformed

        int b;
        for (b = 0; b < pages.size(); b++) {
            if (getName().equals(select_field.get(b).getName())) {
                break;
            }
        }

        try {
            if (select_field.get(b).getText().equals("")) {
                select_box.setText("can not be empty!");
            } else {
                link((int) Double.parseDouble(select_field.get(b).getText()), getName());
            }
        } catch (IOException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_readActionPerformed
    public static void link(int q, String name) throws FileNotFoundException, IOException {

        lines.clear();

        InputStream inputStream = null;
        int b = 0;

        try {
            String address = "http://www.gutenberg.org/files/" + q + "/" + q + "-0.txt";
            URL openUrl = new URL(address);
            URLConnection httpUrlConnection = openUrl.openConnection();
            inputStream = httpUrlConnection.getInputStream();
        } catch (IOException e) {
            b = 1;
        }
        if (b == 1) {
            try {
                String address = "http://www.gutenberg.org/files/" + q + "/" + q + "-8.txt";
                URL openUrl = new URL(address);
                URLConnection httpUrlConnection = openUrl.openConnection();
                inputStream = httpUrlConnection.getInputStream();

            } catch (IOException e) {
                b = 2;
            }
        }
        if (b == 2) {
            try {
                String address = "http://www.gutenberg.org/files/" + q + "/" + q + ".txt";
                URL openUrl = new URL(address);
                URLConnection httpUrlConnection = openUrl.openConnection();
                inputStream = httpUrlConnection.getInputStream();

            } catch (IOException e) {
                b = 3;
            }
        }
        if (b != 3) {

            try ( BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(inputStream))) {
                String line = "";
                while ((line = bufferedReader.readLine()) != null) {
                    lines.add(line);
                }
            }
            String q1 = String.valueOf(q);
            File file = new File("Books\\" + q1 + ".txt");
            if (!file.exists()) {
                file.createNewFile();
            }
            FileWriter fileWriter = new FileWriter(file, false);
            int s;
            for (s = 0; s < bookwindow.size(); s++) {
                if (bookwindow.get(s).getName().equals(name)) {
                    break;

                }
            }
            bookwindow.get(s).setTitle("Anonim");
            bookwindow.get(s).setVisible(true);
            try ( BufferedWriter bWriter = new BufferedWriter(fileWriter)) {
                int a = 0;
                while (a < lines.size()) {
                    bWriter.write(lines.get(a) + "\n");
                    read_form.append(lines.get(a) + "\n");
                    a++;
                }
                read_form.setCaretPosition(0);
            }
        } else {
            int b1;
            for (b1 = 0; b1 < pages.size(); b1++) {
                if (name.equals(select_field.get(b1).getName())) {
                    break;
                }
            }
            select_box.setText("There is no such book or sound book.");
        }
    }
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        int s = 0;
        do {

            int b;
            for (b = 0; b < pages.size(); b++) {
                if (getName().equals(select_field.get(b).getName())) {
                    break;
                }
            }
            InputStream inputStream = null;
            int h = 0;

            try {
                String address = "http://www.gutenberg.org/files/" + select_field.get(b).getText() + "/" + select_field.get(b).getText() + "-0.txt";
                URL openUrl = new URL(address);
                URLConnection httpUrlConnection = openUrl.openConnection();
                inputStream = httpUrlConnection.getInputStream();
            } catch (IOException e) {
                h = 1;
            }
            if (h == 1) {
                try {
                    String address = "http://www.gutenberg.org/files/" + select_field.get(b).getText() + "/" + select_field.get(b).getText() + "-8.txt";
                    URL openUrl = new URL(address);
                    URLConnection httpUrlConnection = openUrl.openConnection();
                    inputStream = httpUrlConnection.getInputStream();

                } catch (IOException e) {
                    h = 2;
                }
            }
            if (h == 2) {
                try {
                    String address = "http://www.gutenberg.org/files/" + select_field.get(b).getText() + "/" + select_field.get(b).getText() + ".txt";
                    URL openUrl = new URL(address);
                    URLConnection httpUrlConnection = openUrl.openConnection();
                    inputStream = httpUrlConnection.getInputStream();

                } catch (IOException e) {
                    h = 3;
                }
            }
            if (h == 3) {
                select_field.get(b).setText("This a sound book!");
                break;
            } else {
                int c;
                for (c = 0; c < AramaSonuçları_numbers.size(); c++) {
                    if (AramaSonuçları_numbers.get(c).equals(select_field.get(b).getText())) {
                        AddBook(AramaSonuçları.get(c), getName());
                        s = 1;
                        break;
                    }
                }
                if (s == 0) {
                    select_field.get(b).setText("Invalid Number!");
                    break;
                }
                String liste = "";
                File files = new File(getName() + ".txt");
                FileWriter fileWriter = null;
                try {
                    fileWriter = new FileWriter(files, true);
                } catch (IOException ex) {
                    Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
                }
                BufferedWriter bWriter = new BufferedWriter(fileWriter);

                if (book1_.get(b).getText().isEmpty()) {
                    book1_.get(b).setText(shelf.get(b).getBooks(0).getName());

                    liste = liste + "1---" + shelf.get(b).getBooks(0).getName() + "---" + AramaSonuçları_numbers.get(c) + "---" + "0" + "\n";
                } else if (book2_.get(b).getText().isEmpty() && bks == 0) {
                    book2_.get(b).setText(shelf.get(b).getBooks(1).getName());

                    liste = liste + "2---" + shelf.get(b).getBooks(1).getName() + "---" + AramaSonuçları_numbers.get(c) + "---" + "0" + "\n";

                } else if (book3_.get(b).getText().isEmpty() && bks == 0) {
                    book3_.get(b).setText(shelf.get(b).getBooks(2).getName());
                    liste = liste + "3---" + shelf.get(b).getBooks(2).getName() + "---" + AramaSonuçları_numbers.get(c) + "---" + "0" + "\n";
                } else if (book4_.get(b).getText().isEmpty() && bks == 0) {
                    book4_.get(b).setText(shelf.get(b).getBooks(3).getName());
                    liste = liste + "4---" + shelf.get(b).getBooks(3).getName() + "---" + AramaSonuçları_numbers.get(c) + "---" + "0" + "\n";
                } else if (book5_.get(b).getText().isEmpty() && bks == 0) {
                    book5_.get(b).setText(shelf.get(b).getBooks(4).getName());
                    liste = liste + "5---" + shelf.get(b).getBooks(4).getName() + "---" + AramaSonuçları_numbers.get(c) + "---" + "0" + "\n";
                } else if (book6_.get(b).getText().isEmpty() && bks == 0) {
                    book6_.get(b).setText(shelf.get(b).getBooks(5).getName());
                    liste = liste + "6---" + shelf.get(b).getBooks(5).getName() + "---" + AramaSonuçları_numbers.get(c) + "---" + "0" + "\n";
                } else if (book7_.get(b).getText().isEmpty() && bks == 0) {
                    book7_.get(b).setText(shelf.get(b).getBooks(6).getName());
                    liste = liste + "7---" + shelf.get(b).getBooks(6).getName() + "---" + AramaSonuçları_numbers.get(c) + "---" + "0" + "\n";
                } else if (book8_.get(b).getText().isEmpty() && bks == 0) {
                    book8_.get(b).setText(shelf.get(b).getBooks(7).getName());
                    liste = liste + "8---" + shelf.get(b).getBooks(7).getName() + "---" + AramaSonuçları_numbers.get(c) + "---" + "0" + "\n";
                } else if (book9_.get(b).getText().isEmpty() && bks == 0) {
                    book9_.get(b).setText(shelf.get(b).getBooks(8).getName());
                    liste = liste + "9---" + shelf.get(b).getBooks(8).getName() + "---" + AramaSonuçları_numbers.get(c) + "---" + "0" + "\n";
                } else if (book10_.get(b).getText().isEmpty() && bks == 0) {
                    book10_.get(b).setText(shelf.get(b).getBooks(9).getName());
                    liste = liste + "10---" + shelf.get(b).getBooks(9).getName() + "---" + AramaSonuçları_numbers.get(c) + "---" + "0" + "\n";
                } else if (!book10_.get(b).getText().isEmpty() && bks == 1) {
                    jTextArea1.setText("");
                    jTextArea1.append("Your shelf is full!");
                }
                try {
                    bWriter.write(liste);
                } catch (IOException ex) {
                    Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    bWriter.close();
                } catch (IOException ex) {
                    Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } while (false);

    }//GEN-LAST:event_addActionPerformed

    private void book1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book1ActionPerformed

    private void Remove1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remove1ActionPerformed
        int b;
        for (b = 0; b < pages.size(); b++) {
            if (getName().equals(pages.get(b).getName())) {
                break;
            }
        }
        users.get(b).removeBook(book1_.get(b), 0);
        shelf.get(b).BookList.remove(0);

    }//GEN-LAST:event_Remove1ActionPerformed

    private void read1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read1ActionPerformed
        int b;
        for (b = 0; b < pages.size(); b++) {
            if (getName().equals(pages.get(b).getName())) {
                break;
            }
        }
        users.get(b).ReadBook(1);
    }//GEN-LAST:event_read1ActionPerformed

    private void Remove2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remove2ActionPerformed
        int b;
        for (b = 0; b < pages.size(); b++) {
            if (getName().equals(pages.get(b).getName())) {
                break;
            }
        }
        users.get(b).removeBook(book2_.get(b), 1);
        shelf.get(b).BookList.remove(1);
    }//GEN-LAST:event_Remove2ActionPerformed

    private void Remove3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remove3ActionPerformed
        int b;
        for (b = 0; b < pages.size(); b++) {
            if (getName().equals(pages.get(b).getName())) {
                break;
            }
        }
        users.get(b).removeBook(book3_.get(b), 2);
        shelf.get(b).BookList.remove(2);
    }//GEN-LAST:event_Remove3ActionPerformed

    private void Remove4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remove4ActionPerformed
        int b;
        for (b = 0; b < pages.size(); b++) {
            if (getName().equals(pages.get(b).getName())) {
                break;
            }
        }
        users.get(b).removeBook(book4_.get(b), 3);
        shelf.get(b).BookList.remove(3);
    }//GEN-LAST:event_Remove4ActionPerformed

    private void Remove5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remove5ActionPerformed
        int b;
        for (b = 0; b < pages.size(); b++) {
            if (getName().equals(pages.get(b).getName())) {
                break;
            }
        }
        users.get(b).removeBook(book5_.get(b), 4);
        shelf.get(b).BookList.remove(4);
    }//GEN-LAST:event_Remove5ActionPerformed

    private void Remove6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remove6ActionPerformed
        int b;
        for (b = 0; b < pages.size(); b++) {
            if (getName().equals(pages.get(b).getName())) {
                break;
            }
        }
        users.get(b).removeBook(book6_.get(b), 5);
        shelf.get(b).BookList.remove(5);
    }//GEN-LAST:event_Remove6ActionPerformed

    private void Remove7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remove7ActionPerformed
        int b;
        for (b = 0; b < pages.size(); b++) {
            if (getName().equals(pages.get(b).getName())) {
                break;
            }
        }
        users.get(b).removeBook(book7_.get(b), 6);
        shelf.get(b).BookList.remove(6);
    }//GEN-LAST:event_Remove7ActionPerformed

    private void Remove8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remove8ActionPerformed
        int b;
        for (b = 0; b < pages.size(); b++) {
            if (getName().equals(pages.get(b).getName())) {
                break;
            }
        }
        users.get(b).removeBook(book8_.get(b), 7);
        shelf.get(b).BookList.remove(7);

    }//GEN-LAST:event_Remove8ActionPerformed

    private void Remove9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remove9ActionPerformed
        int b;
        for (b = 0; b < pages.size(); b++) {
            if (getName().equals(pages.get(b).getName())) {
                break;
            }
        }
        users.get(b).removeBook(book9_.get(b), 8);
        shelf.get(b).BookList.remove(8);
    }//GEN-LAST:event_Remove9ActionPerformed

    private void Remove10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remove10ActionPerformed
        int b;
        for (b = 0; b < pages.size(); b++) {
            if (getName().equals(pages.get(b).getName())) {
                break;
            }
        }
        users.get(b).removeBook(book10_.get(b), 9);
        shelf.get(b).BookList.remove(9);
    }//GEN-LAST:event_Remove10ActionPerformed

    private void read2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read2ActionPerformed
        int b;
        for (b = 0; b < pages.size(); b++) {
            if (getName().equals(pages.get(b).getName())) {
                break;
            }
        }
        users.get(b).ReadBook(2);        // TODO add your handling code here:
    }//GEN-LAST:event_read2ActionPerformed

    private void read5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read5ActionPerformed
        int b;
        for (b = 0; b < pages.size(); b++) {
            if (getName().equals(pages.get(b).getName())) {
                break;
            }
        }
        users.get(b).ReadBook(5);       // TODO add your handling code here:
    }//GEN-LAST:event_read5ActionPerformed

    private void book5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book5ActionPerformed

    private void read3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read3ActionPerformed
        int b;
        for (b = 0; b < pages.size(); b++) {
            if (getName().equals(pages.get(b).getName())) {
                break;
            }
        }
        users.get(b).ReadBook(3);         // TODO add your handling code here:
    }//GEN-LAST:event_read3ActionPerformed

    private void read4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read4ActionPerformed
        int b;
        for (b = 0; b < pages.size(); b++) {
            if (getName().equals(pages.get(b).getName())) {
                break;
            }
        }
        users.get(b).ReadBook(4);        // TODO add your handling code here:
    }//GEN-LAST:event_read4ActionPerformed

    private void read7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read7ActionPerformed
        int b;
        for (b = 0; b < pages.size(); b++) {
            if (getName().equals(pages.get(b).getName())) {
                break;
            }
        }
        users.get(b).ReadBook(7);        // TODO add your handling code here:
    }//GEN-LAST:event_read7ActionPerformed

    private void read8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read8ActionPerformed
        int b;
        for (b = 0; b < pages.size(); b++) {
            if (getName().equals(pages.get(b).getName())) {
                break;
            }
        }
        users.get(b).ReadBook(8);         // TODO add your handling code here:
    }//GEN-LAST:event_read8ActionPerformed

    private void read9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read9ActionPerformed
        int b;
        for (b = 0; b < pages.size(); b++) {
            if (getName().equals(pages.get(b).getName())) {
                break;
            }
        }
        users.get(b).ReadBook(9);        // TODO add your handling code here:
    }//GEN-LAST:event_read9ActionPerformed

    private void read10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read10ActionPerformed
        int b;
        for (b = 0; b < pages.size(); b++) {
            if (getName().equals(pages.get(b).getName())) {
                break;
            }
        }
        users.get(b).ReadBook(10);         // TODO add your handling code here:
    }//GEN-LAST:event_read10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new HomePage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Remove1;
    private javax.swing.JButton Remove10;
    private javax.swing.JButton Remove2;
    private javax.swing.JButton Remove3;
    private javax.swing.JButton Remove4;
    private javax.swing.JButton Remove5;
    private javax.swing.JButton Remove6;
    private javax.swing.JButton Remove7;
    private javax.swing.JButton Remove8;
    private javax.swing.JButton Remove9;
    public static javax.swing.JButton add;
    public static javax.swing.JTextField book1;
    public static javax.swing.JTextField book10;
    public static javax.swing.JTextField book2;
    public static javax.swing.JTextField book3;
    public static javax.swing.JTextField book4;
    public static javax.swing.JTextField book5;
    public static javax.swing.JTextField book6;
    public static javax.swing.JTextField book7;
    public static javax.swing.JTextField book8;
    private javax.swing.JTextField book812312312;
    public static javax.swing.JTextField book9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea jTextArea1;
    public static javax.swing.JTextField jTextField1;
    public static javax.swing.JButton read;
    private javax.swing.JButton read1;
    private javax.swing.JButton read10;
    private javax.swing.JButton read2;
    private javax.swing.JButton read3;
    private javax.swing.JButton read4;
    private javax.swing.JButton read5;
    private javax.swing.JButton read6;
    private javax.swing.JButton read7;
    private javax.swing.JButton read8;
    private javax.swing.JButton read9;
    private javax.swing.JButton search;
    public static javax.swing.JTextField search_field;
    public static javax.swing.JTextField select_box;
    // End of variables declaration//GEN-END:variables
}
