package Guthenberg;

import static Guthenberg.Guthenberg.read_book_area;
import static Guthenberg.Guthenberg.rem;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Reader;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 90505
 */
public class windowread extends javax.swing.JFrame {

    /**
     * Creates new form windowread
     */
    public windowread() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        read_form = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        read_form.setColumns(20);
        read_form.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        read_form.setRows(5);
        jScrollPane1.setViewportView(read_form);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setText("Exit ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jLabel1.setText("Put -!- to where you left ");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jLabel2.setText("from reading");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int z = 0;
        String[] split = null;
        for (z = 0; z < read_book_area.size(); z++) {
            if (read_book_area.get(z).getName().equals(getName())) {
                split = read_book_area.get(z).getText().split("\\n");

            }
        }

        //read_form.getLineCount();
        //int indexOf = 0;
        int k = 0;
        String[] son = null;
        for (k = 0; k < split.length; k++) {
            if (split[k].contains("-!-")) {
                son = split[k].split("-!-", 2); //indexOf = split[k].indexOf("*");
                break;
            }
        }

        read_book_area.get(0).setText("");

        File filem = new File(getName() + ".txt");

        Reader fileReader = null;

        try {
            fileReader = new FileReader(filem);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(windowread.class.getName()).log(Level.SEVERE, null, ex);
        }

        BufferedReader oku = new BufferedReader(fileReader);

        String line1 = "";
        rem.clear();
        try {
            while ((line1 = oku.readLine()) != null) {
                //linesplit = line.split("---");
                rem.add(line1);

            }
        } catch (IOException ex) {
            Logger.getLogger(windowread.class.getName()).log(Level.SEVERE, null, ex);
        }
        String[] a3 = null;
        int s3;


        for (s3 = 0; s3 < rem.size(); s3++) {
            if (rem.get(s3).split("---")[0].equals(getTitle())) {
                a3 = rem.get(s3).split("---");
                break;
            }
        }
        try {
            if (k == split.length) {
                k = 0;
            }
            int j1 = k;//satır sayısı

            for (int h = 0; h < j1; h++) {
                k = k + split[h].length();
            }
            k = k + son[0].length();
            if (a3.length > 3) {
                a3[3] = String.valueOf(k);
                rem.set(s3, a3[0] + "---" + a3[1] + "---" + a3[2] + "---" + a3[3]);
            }
           
            String j = rem.get(s3);

            if (a3.length == 3) {
                rem.set(s3, j + "---" + k);
            }

            FileWriter fileWriter = null;
            try {
                fileWriter = new FileWriter(filem, false);
            } catch (IOException ex) {
                Logger.getLogger(windowread.class.getName()).log(Level.SEVERE, null, ex);
            }
            BufferedWriter bWriter = new BufferedWriter(fileWriter);
            String liste = "";
            for (int hj = 0; hj < rem.size(); hj++) {
                liste = liste + rem.get(hj) + "\n";
            }
            try {
                bWriter.write(liste);
            } catch (IOException ex) {
                Logger.getLogger(windowread.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                bWriter.close();
            } catch (IOException ex) {
                Logger.getLogger(windowread.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (Exception e) {

        }

        dispose();        // TODO add your handling code here:


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(windowread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new windowread().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea read_form;
    // End of variables declaration//GEN-END:variables
}
